configs:
  wan.json:
    content: |
      {
        "dt": "2022-01-20T12:57:59.823350+00:00",
        "wan": {
            "dt": "2022-01-20T12:57:59.823350+00:00",
            "curls": ["tcp://127.0.0.1:5632/", "http://127.0.0.1:5642/"]
        }
      }
  wil.json:
    content: |
      {
        "wil": {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "curls": ["tcp://127.0.0.1:5633/", "http://127.0.0.1:5643/"]
        },
        "dt": "2022-01-20T12:57:59.823350+00:00"
      }
  wes.json:
    content: |
      {
        "wes": {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "curls": ["tcp://127.0.0.1:5634/", "http://127.0.0.1:5644/"]
        },
        "dt": "2022-01-20T12:57:59.823350+00:00"
      }
  wit.json:
    content: |
      {
        "wit": {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "curls": ["tcp://127.0.0.1:5635/", "http://127.0.0.1:5645/"]
        },
        "dt": "2022-01-20T12:57:59.823350+00:00"
      }

x-healthcheck: &healthcheck
  interval: 2s
  timeout: 3s
  retries: 5
  start_period: 2s

x-python-env: &python-env
  PYTHONUNBUFFERED: 1
  PYTHONIOENCODING: UTF-8

services:
  vlei-server:
    image: gleif/vlei
    environment:
      <<: *python-env
    stop_grace_period: 0s
    command: vLEI-server -s ./schema/acdc -c ./samples/acdc/ -o ./samples/oobis/
    healthcheck:
      test: curl -f http://localhost:7723/oobi/EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao
      <<: *healthcheck
    ports:
      - 7723:7723

  witness-demo:
    image: weboftrust/keri-witness-demo:1.1.0
    environment:
      <<: *python-env
    stop_grace_period: 0s
    healthcheck:
      test: curl -f http://localhost:5642/oobi
      <<: *healthcheck
    configs:
      - source: wan.json
        target: /keripy/scripts/keri/cf/main/wan.json
      - source: wil.json
        target: /keripy/scripts/keri/cf/main/wil.json
      - source: wes.json
        target: /keripy/scripts/keri/cf/main/wes.json
      - source: wit.json
        target: /keripy/scripts/keri/cf/main/wit.json
    ports:
      - 5642:5642
      - 5643:5643
      - 5644:5644
