#!/usr/bin/env python
from keri.core.coring import MtrDex, Matter, Sizage
from keri.core.indexing import IdrDex, Indexer, Xizage
from keri.core.counting import CtrDex_1_0, CtrDex_2_0, Counter, Cizage
from json import dumps


def format_size(sizes: dict[str, Cizage | Xizage | Sizage]) -> str:
    result = dict()
    for key, size in sizes.items():
        if not key.startswith("__"):
            result[key] = {
                "hs": size.hs,
                "ss": size.ss,
                "os": size.os if hasattr(size, "os") else 0,
                "fs": size.fs or 0,
                "ls": size.ls if hasattr(size, "ls") and size.ls else 0,
                "xs": size.xs if hasattr(size, "xs") and size.ls else 0,
            }

    return dumps(result)


print("// THIS FILE IS AUTO-GENERATED")
print("// DO NOT EDIT THIS FILE DIRECTLY")
print("// Use scripts/generate-codec.py to generate this file")

print(f"export const MatterTable = {format_size(Matter.Sizes)}")
print(f"export const CountTable_10 = {format_size(Counter.Sizes.get(1).get(0))}")
print(f"export const CountTable_20 = {format_size(Counter.Sizes.get(2).get(0))}")
print(f"export const IndexTable = {format_size(Indexer.Sizes)}")

print(f"export const MatterCode = {dumps(MtrDex.__dict__)}")
print(f"export const CountCode_10 = {dumps(CtrDex_1_0.__dict__)}")
print(f"export const CountCode_20 = {dumps(CtrDex_2_0.__dict__)}")
print(f"export const IndexCode = {dumps(IdrDex.__dict__)}")
